# https://hyperskill.org/projects/374/stages/2232/implement
# https://docs.docker.com/compose/gettingstarted/
# https://hub.docker.com/_/mongo
# https://docs.docker.com/reference/compose-file/version-and-name/
# Defining environment variables in docker compose files:
# https://docs.docker.com/compose/how-tos/environment-variables/set-environment-variables/#use-the-environment-attribute
# https://docs.docker.com/compose/intro/compose-application-model/#illustrative-example

# docker compose up --help                                                                                        
# docker compose --env-file .env up 
# docker compose --env-file .env --project-name hyper-mongo up 
# docker compose --env-file .env --project-name hyper-mongo up -d
# to stop and remove the container: docker compose down
# to only stop the container: docker compose stop
# if container already exists you can start it with: docker compose start
# http://localhost:27027/

# define services in a Compose file
# "It looks like you are trying to access MongoDB over HTTP on the native driver port."

version: '3.1'
name: hyper-mongo   # this is the name of the container made from docker compose up

services:
  mongodb:
    
    image: mongo:6.0.8
    container_name: hyper-mongo
    ports:
      - "27027:27017"
    env_file: ['.env']
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - hyper-task-manager-network

volumes:
  mongo-data:
networks:
  hyper-task-manager-network:  

